package com.android.thememanager.controller.online;

import com.android.thememanager.settings.superwallpaper.C2656k;
import com.android.thememanager.util.C2755a;

/* JADX INFO: renamed from: com.android.thememanager.controller.online.p */
/* JADX INFO: compiled from: OnlineProtocolConstants.java */
/* JADX INFO: loaded from: classes2.dex */
public interface InterfaceC1925p extends InterfaceC1932s {
    public static final String a0 = "designer";
    public static final String a0w;
    public static final String a4 = "status";
    public static final String a5le = "score";
    public static final String a7 = "source";
    public static final String a7on = "hideIncompatible";
    public static final String a95z = "isSubject";
    public static final String ad8 = "errcode";
    public static final String ads1 = "ignoreAd";
    public static final String ae9n = "pageSize";
    public static final String afni = "login";
    public static final String agdp = "orderInfo";
    public static final String agf = "actionUrl";
    public static final String aix = "All%s";
    public static final String aiyx = "tagId";
    public static final String aojq = "accountVerify";
    public static final String apb;
    public static final String arkx = "layoutRow";
    public static final String asr;
    public static final String aw19 = "keywords";
    public static final String b03g;
    public static final String b1ty = "frontCover";
    public static final String b2bv = "maxUpdateTime";
    public static final String b7h = "rank_count1";
    public static final String b7sa = "fileshash";
    public static final String ba7 = "modifyTime";
    public static final String bb1 = "list";
    public static final String bb8 = "name";
    public static final String bb9p = "Fine";
    public static final String bd84 = "webDownload";
    public static final String bewm = "interval";
    public static final String bgz = "userType";
    public static final String bk3;
    public static final String bklz = "receiverName";
    public static final String blj = "onShelf";
    public static final String blsz = "dailyData";
    public static final String bo7 = "globalStrategy";
    public static final String bou5 = "used";
    public static final String bvq;
    public static final String bvt = "pageConfig";
    public static final String bxas;
    public static final String byb3 = "productIndex";
    public static final String byf = "height";
    public static final String c4zs = "GroupItem";
    public static final String c59w;
    public static final String c7j = "wallpapers";
    public static final String c7tw = "count";
    public static final String cbcd = "gift";
    public static final String cdhb = "downloadUrl";
    public static final String ce2 = "description";
    public static final String cg = "tips";
    public static final String cgz = "dl.w.xk.miui.com";
    public static final String cjs = "tagIds";
    public static final String cm = "items";
    public static final String crp8;
    public static final String ctl4 = "actions";
    public static final String cuep;
    public static final String cxw = "tagId";
    public static final String czt = "dataVip";
    public static final String d2 = "like";
    public static final String d7ek = "miuiUIVersion";
    public static final String d98 = "packageName";
    public static final String dci = "picUrl";
    public static final String de9w = "categoryName";
    public static final String dew6 = "picUrlRoot";
    public static final String dg = "price";
    public static final String dota = "iconUrl";
    public static final String dpl2 = "number";
    public static final String dqa = "snapshotsUrl";
    public static final String dqjj = "cUserId";
    public static final String dsx;
    public static final String dtf = "giftId";
    public static final String du = "serviceToken";
    public static final String dv5 = "content";
    public static final String dymb;
    public static final String e0l;
    public static final String e3la = "endTime";
    public static final String e58q = "subhash";
    public static final String e63j = "alpha";
    public static final String e6x = "https://zhuti.xiaomi.com/themeActivity/views/activities/index.html?activity-id=fc8b5464-332e-430a-a6b8-730b8dd547f5&webBitFlag=7&region=CN&isGlobal=false&language=zh-CN";
    public static final String e7ie = "hash";
    public static final String ea = "currentTheme";
    public static final String eb;
    public static final String eg2 = "http://zhuti.xiaomi.com/detail/%s";
    public static final String egc1 = "downloads";
    public static final String en = "webBitFlag";
    public static final String enbq = "showType";
    public static final String eov = "snapshotsUrlSize";
    public static final String eovq;
    public static final String esx1 = "star";
    public static final String eyzx = "extraInfo";
    public static final String f5 = "trialDialogMessage";
    public static final String f517 = "auth";
    public static final String f7sp = "xRef";
    public static final String f8 = "isGlobal";
    public static final String f8i = "layoutCol";
    public static final String fd7p;
    public static final String ffiu = "pageMetas";
    public static final String fmq;
    public static final String foll = "comments";
    public static final String fp = "apiVersion";
    public static final String fpd = "signature";
    public static final String ft4;
    public static final String ftn = "total";
    public static final String fwd = "ok";
    public static final String fx = "themeDetail";
    public static final String fy7 = "webp/w%s/";
    public static final String fz0t = "userName";
    public static final String fzr = "scene";
    public static final String fzz = "wallpaperId";
    public static final String g3a = "fileHash";
    public static final String g5n4 = "webResource";
    public static final String g8pn = "items";
    public static final String gb1 = "hideManualHiding";
    public static final String gd7z = "extra";
    public static final String gdzl = "m.zhuti.xiaomi.com";
    public static final String ggnn;
    public static final String giq0 = "ignoreAdIds";
    public static final String gle;
    public static final String glf = "isPersonalizedAdEnabled";
    public static final String gm2h = "index";
    public static final String gn7j;
    public static final String gwe;
    public static final String gwj;
    public static final String gx4;
    public static final String gym = "count";
    public static final String h2 = "type";
    public static final String h8 = "author";
    public static final String h97 = "currentWallpaperType";
    public static final String h9i4 = "trackId";
    public static final String h9w7 = "width";
    public static final String ha;
    public static final String hd;
    public static final String hf = "ex";
    public static final String hhpi = "_more";
    public static final String hjp = "region";
    public static final String hkfy = "payload";
    public static final String hm43;
    public static final String hm6 = "language";
    public static final String hn4z = "productId";
    public static final String hohe;
    public static final String huhj;
    public static final String husj = "landingPageUrl";
    public static final String hwpi = "packIds";
    public static final String hx5d = "category";
    public static final String i05 = "localStrategy";
    public static final String i0fv = "startDownload";
    public static final String i1r = "page/v3/mifold-setting-%s";
    public static final String i2 = "http://resolver.gslb.mi-idc.com/gslb/gslb/getbucket.asp";
    public static final String i2en = "outsideUrl";
    public static final String i51 = "senderName";
    public static final String i55 = "apiCode";
    public static final String i5c;
    public static final String i6 = "toUse";
    public static final String i7x;
    public static final String i97;
    public static final String i99y = "favorite_theme_list";
    public static final String idln = "vaid";
    public static final String ifu = "Purchased%s";
    public static final String ig;
    public static final String igdj = "giftType";
    public static final String igv = "actionType";
    public static final String iip;
    public static final String il;
    public static final String im = "downloadUrlRootAudio";
    public static final String im8v = "%sFine";
    public static final String imy = "personal";
    public static final String io = "https://zhuti.xiaomi.com/wallpaperSubject?uuid=%s";
    public static final String ioq = "productId";
    public static final String ivf = "pageCategory";
    public static final String ivg;
    public static final String iw2p = "redeem";
    public static final String iya = "gifts";
    public static final String iz1i = "versionCode";
    public static final String izd = "toUserKey";
    public static final String j0 = "productBought";
    public static final String j60k = "messageType";
    public static final String j8wd = "downloadUrlRoot";
    public static final String jar = "dot";
    public static final String ji83 = "imgUrls";
    public static final String jk2 = "headerPic";
    public static final String jky = "productIds";
    public static final String jom = "trialTime";
    public static final String jpkh = "title";
    public static final String jqd;
    public static final String jt = "randIndex";
    public static final String jtf = "page/v3/mipad-setting-%s";
    public static final String jua8 = "pageMetaCount";
    public static final String jvci = "10";
    public static final String k2gn = "gift";
    public static final String k3v9 = "adcontrol";
    public static final String k4 = "Like%s";
    public static final String k5dw;
    public static final String k7 = "SortNotFree";
    public static final String k7ck = "host";
    public static final String kbf0 = "layoutTop";
    public static final String kf = "sendTimes";
    public static final String kff = "page";
    public static final String kfxm = "samedesign_%s";
    public static final String kg = "count";
    public static final String khz = "descriptionPic";
    public static final String kls = "orderFee";
    public static final String kn = "hwVersion";
    public static final String koyb = "versionName";
    public static final String kpsf = "code";
    public static final String krlr = "Cookie";
    public static final String kw5 = "tags";
    public static final String kxwi = "category";
    public static final String kyz8;
    public static final String kz6x = "retCode";
    public static final String l044 = "xTrackId";
    public static final String l0e = "WALLPAPER_INDEX";
    public static final String l1l1 = "flag";
    public static final String l24 = "designer";
    public static final String l2gm;
    public static final String l3h = "usedThemesHistory";
    public static final String l49c = "freeResult";
    public static final String l5 = "system";
    public static final String l8 = "followerName";
    public static final String l9;
    public static final String lg18 = "name";
    public static final String lge8 = "pageGroup";
    public static final String lj = "uiVersion";
    public static final String lk4;
    public static final String lki0 = "picUrlRoot";
    public static final String lkw = "value";
    public static final String lm3 = "packIds";
    public static final String lmz = "giftId";
    public static final String lo = "subjectUrl";
    public static final String loce;
    public static final String lq1p;
    public static final String lqk8;
    public static final String lro = "custom.zhuti.xiaomi.com";
    public static final String ls = "pointCount";
    public static final String lwce = "cardStart";
    public static final String m0 = "page";
    public static final String m2 = "msg";
    public static final String m3 = "PurchasedOld";
    public static final String m5pq = "layoutCols";
    public static final String m76 = "owned";
    public static final String m9u = "autolaunch";
    public static final String ma = "packType";
    public static final String mcy = "unSubTagIds";
    public static final String mddg = "All";
    public static final String me = "ringtoneUrl";
    public static final String mk = "maxCount";
    public static final String mkxg = "purchased_theme_list";
    public static final String ml5 = "oaid";
    public static final String mm = "/detail/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*";
    public static final String mp = "clickMonitorUrls";
    public static final String mp7a = "requestedCount";
    public static final String mqz;
    public static final String mtwi = "ReceivedGifts";
    public static final String mug = "deviceType";
    public static final String mwew;
    public static final String mzq = "appStoreDownloadUrl";
    public static final String n0wh = "ref";
    public static final String n2wl;
    public static final String n551 = "moduleId";
    public static final String n7r = "relatedId";
    public static final String n9t;
    public static final String n9v = "targetType";
    public static final String ncfu = "userId";
    public static final String nea = "device";
    public static final String nf = "pageId";
    public static final String nh;
    public static final String njq = "isLike";
    public static final String nlg = "data";
    public static final String nmft = "downloadupdate";
    public static final String nn = "id";
    public static final String nnx;
    public static final String nou = "_sign";
    public static final String np = "everything";
    public static final String nr = "rank_count3";
    public static final String nsr = "orderId";
    public static final String nt6s = "suitId";
    public static final String nvs3 = "shopWindowCols";
    public static final String nw;
    public static final String nzoy = "likeCount";
    public static final String o1sk = "nosend";
    public static final String o6t = "SortFree";
    public static final String o7h = "score";
    public static final String o9ja = "version";
    public static final String oa6p = "subhashType";
    public static final String ocl = "smallVideoUrl";
    public static final String oe42 = "VIDEO_WP_INDEX";
    public static final String oeke;
    public static final String ohc0 = "webp/w%sq%s/";
    public static final String ojf7;
    public static final String ok4l;
    public static final String oklc;
    public static final String oml3;
    public static final String omp0;
    public static final String on = "commentId";
    public static final String onc0 = "model";
    public static final String onr;
    public static final String ooq6 = "originPrice";
    public static final String or1;
    public static final String os4s = "toCommentId";
    public static final String otl = "start";
    public static final String ou1;
    public static final String ow8;
    public static final String oy = "guid";
    public static final String p05g = "nickname";
    public static final String p1s7;
    public static final String p4g;
    public static final String p69;
    public static final String p7p2 = "WALLPAPER_DETAIL_RIGHT";
    public static final String pavv = "starCountSize";
    public static final String pe6o = "xPrevRef";
    public static final String pia;
    public static final String pisc;
    public static final String pjp = "ft";
    public static final String pkq2 = "fileSize";
    public static final String pnh = "send";
    public static final String ppa = "relatedType";
    public static final String psl;
    public static final String pstq = "md5";
    public static final String pt6 = "apkSize";
    public static final String pw6a = "parameters";
    public static final String pwbu = "title";
    public static final String pwo = "flags";
    public static final String pxz;
    public static final String q1j = "sortList";
    public static final String q3 = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}";
    public static final String q68v = "id";
    public static final String q6c = "adCountry";
    public static final String q7yl = "source";
    public static final String q9e = "name";
    public static final String qbxp = "isSenderAnonymous";
    public static final String qcx;
    public static final String qdd;
    public static final String qhv = "uuid";
    public static final String qhx = "payResult";
    public static final String qj = "addActionLog";
    public static final String qjn = "freeCode";
    public static final String qk = "rank_count4";
    public static final String qn = "key";
    public static final String qncf = "sendLimit";
    public static final String qp94 = "tagIds";
    public static final String qps = "giftName";
    public static final String r07n = "isAnonymous";
    public static final String r3 = "title";
    public static final String r58;
    public static final String r61 = "PurchasedOld%s";
    public static final String rax = "Local";
    public static final String rd5 = "WALLPAPER_DETAIL_BELOW";
    public static final String rek;
    public static final String rg7 = "template";
    public static final String rkfn;
    public static final String rkxl = "pageKey";
    public static final String rp0 = "%sClazz";
    public static final String rr = "http://zhuti.xiaomi.com/detail/share/%s";
    public static final String rr7 = "createTime";
    public static final String rrtv = "cardCount";
    public static final String rst;
    public static final String ru8 = "analytics";
    public static final String s0i = "apk";
    public static final String s0z1 = "allDownloadNum";
    public static final String s2kp = "http://zhuti.xiaomi.com/redeem?key=%s";
    public static final String s6x2 = "rank_count2";
    public static final String s7;
    public static final String s9y = "THEME_DETAIL";
    public static final String sd = "layoutLeft";
    public static final String sn = "adwatermark";
    public static final String sr = "useralsolike";
    public static final String srp = "productPrice";
    public static final String st = "designerMiId";
    public static final String su;
    public static final String sxq = "tags";
    public static final String sy9g;
    public static final String t7j = "packageName";
    public static final String ta9a = "isEnding";
    public static final String tgj1 = "subscribers";
    public static final String tgkg = "updateTime";
    public static final String tgr = "result";
    public static final String tk5o = "relatedId";
    public static final String tlc = "Clazz";
    public static final String tm = "payloadLocator";
    public static final String tm71 = "lastUpdateTime";
    public static final String tn4 = "moduleId";
    public static final String tor2 = "zhuti.xiaomi.com";
    public static final String tpl = "modulesFlag";
    public static final String tpq = "code";
    public static final String tre1 = "value";
    public static final String tt;
    public static final String ttpr = "networkType";
    public static final String tvyk = "brief";
    public static final String tx8q = "restrictImei";
    public static final String ty3d = "share";
    public static final String tzg = "PurchasedGifts";
    public static final String u02 = "packId";
    public static final String u0jg = "type";
    public static final String u1j = "category";
    public static final String u2 = "capability";
    public static final String u74 = "productName";
    public static final String u7mb;
    public static final String u7oz = "hideOtherDevice";
    public static final String u9o;
    public static final String u9q = "status";
    public static final String ucas = "trialDialogTitle";
    public static final String uf5 = "subTagIds";
    public static final String ugm = "commentValue";
    public static final String uhu = "designerId";
    public static final String ul9p = "score";
    public static final String up = "commentValue";
    public static final String uqa = "https://custom.zhuti.xiaomi.com/api/weChat/getWxAcodeUnlimit";
    public static final String ur0a = "productId";
    public static final String uw73 = "color";
    public static final String ux0 = "productSubType";
    public static final String v0;
    public static final String v1uh;
    public static final String v2 = "NonLocal%s";
    public static final String v2k = "https://zhuti.xiaomi.com/detail/share/%s";
    public static final String v4 = "moduleIds";
    public static final String v5fy = "assemblyId";
    public static final String v7x = "identityToken";
    public static final String v9 = "trackIds";
    public static final String v9ed = "contentType";
    public static final String vaso = "NonLocal";
    public static final String ve1q = "hot";
    public static final String vi = "lastUpdateTime";
    public static final String vog = "purchaseCount";
    public static final String vqy = "apiData";
    public static final String vu = "entryType";
    public static final String vu3v = "value";
    public static final String vvj = "3";
    public static final String vwlh = "rank_count5";
    public static final String vx = "otherUrl";
    public static final String vx4g = "%sLocal";
    public static final String vyee = "follow";
    public static final String w1 = "ver";
    public static final String w2q = "homeOpenCount";
    public static final String w2q9 = "userName";
    public static final String w3u7 = "searchType";
    public static final String w4de = "columnStart";
    public static final String w4j4 = "imei";
    public static final String w7ud;
    public static final String wa = "hasRecommend";
    public static final String wbu = "versionName";
    public static final String wc = "suitIds";
    public static final String wde = "averageScore";
    public static final String wg = "%sSortFree";
    public static final String wgc;
    public static final String wj;
    public static final String wl = "sended";
    public static final String woar;
    public static final String wp = "shopWindowViews";
    public static final String wwa = "%sSortNotFree";
    public static final String wy14 = "count";
    public static final String x2z = "type";
    public static final String x41 = "starCount";
    public static final String x76 = "trialButtonTitle";
    public static final String x8sl = "freshInterval";
    public static final String x9 = "buttonTips";
    public static final String x9e = "moduleType";
    public static final String x9f2 = "identityUrl";
    public static final String xavr = "Favorite";
    public static final String xk9p = "hideFree";
    public static final String xkf;

    @Deprecated
    public static final String xkj = "https://zhuti.xiaomi.com/newActivity/toutiaoRecommend?Pid=%s&Uid=%s&Reqid=%s&Resolution=%s&UidType=%s&ImgNum=%s";
    public static final String xky;
    public static final String xleu = "devicePixel";
    public static final String xoi;
    public static final String xq = "pageItemViews";
    public static final String xq3b = "version";
    public static final String xt = "themeDetailUIVersion";
    public static final String xt8;
    public static final String xyt = "pointValue";
    public static final String xzp = "beginTime";
    public static final String xzve = "apiversion";
    public static final String y0 = "productIds";
    public static final String y6xt = "bigVideoUrl";
    public static final String y84p;
    public static final String y8mq = "Purchased";
    public static final String yh = "https://iring.diyring.cc/friendv2/23a539db75168208?wno=%s#login";
    public static final String yhcu = "clazzNameMap";
    public static final String yhe = "title";
    public static final String yhsc = "resource";
    public static final String yiy0 = "width";
    public static final String ynka = "Like";
    public static final String ypv = "Favorite%s";
    public static final String yqyp = "productId";
    public static final String yxk = "downloadMonitorUrls";
    public static final String yzs4;
    public static final String z6f = "viewMonitorUrls";
    public static final String zhll;
    public static final String zht = "contentId";
    public static final String zj2n = "sendTime";
    public static final String zjv = "tags";
    public static final String zky5;
    public static final String zogz = "orderType";
    public static final String zqoj = "updateLogs";
    public static final String zr = "FOLLOWER";
    public static final String zs = "tag";
    public static final String zvd4 = "deeplink";
    public static final String zvz = "serverToast";
    public static final String zz = "title";

    static {
        String strCdj = com.android.thememanager.basemodule.network.theme.f7l8.cdj();
        rkfn = strCdj;
        bxas = C2755a.f16309n;
        String strKi = com.android.thememanager.basemodule.network.theme.f7l8.ki();
        v0 = strKi;
        bvq = strCdj + "page/v2/%s";
        huhj = strCdj + "recordUserAction";
        u9o = strCdj + "page/v3/subjects/%s";
        zhll = strCdj + "page/v3/recommend";
        xky = strKi + "uipages/slide/subjects/%s";
        y84p = strKi + "uipages/slide/wallpaper";
        ou1 = strKi + "uipages/settings/theme";
        String str = strCdj + "page/v3";
        wgc = str;
        u7mb = strCdj + "page/v3/classification";
        w7ud = strKi + "settings/wallpapers/categories";
        xoi = strKi + "settings/wallpapers/categories/%s";
        gwe = strKi + "uipages/settings/font";
        asr = strKi + "safe/auth/myPurchased";
        xkf = strKi + "safe/auth/myFavorite";
        oeke = strKi + "scorewall/config";
        hd = strKi + qj;
        pxz = strKi + "bullet";
        il = strCdj + "subject/key/%sSortFree";
        dsx = strCdj + "subject/key/%sSortNotFree";
        fmq = strKi + "safe/uipages/theme/encourageAdInfo/%s";
        lqk8 = strKi + "safe/uipages/theme/notifiedEncourageAdDone/%s";
        nnx = strKi + "safe/uipages/theme/encourageAdCount/%s";
        omp0 = strCdj + "page/key/%sSortFree";
        psl = strCdj + "page/key/%sSortNotFree";
        hohe = strCdj + "page/key/%sFine";
        loce = strCdj + "page/key/%sClazz";
        yzs4 = str + "/search/key";
        or1 = strCdj + "page/key/%sIndex";
        s7 = strCdj + C2656k.f15718s;
        p4g = strKi + "uipages/search/video/index";
        a0w = strCdj + "search/suggestion";
        ivg = strKi + "products/%s";
        k5dw = strKi + "safe/products/%s";
        pia = strCdj + "download/v2/%s";
        oklc = strCdj + "diff/download/v2/%s";
        xt8 = strCdj + "download/notify";
        ow8 = strCdj + "native/downV3";
        nw = strCdj + "nologin/down";
        ggnn = strCdj + "native/createOrderV2";
        gn7j = strCdj + "native/payByVip";
        jqd = strCdj + "config/clazz/%s/zh-cn";
        onr = strCdj + "recommendation/list/%s";
        su = strCdj + "checkupdate/hashpair";
        crp8 = strCdj + "relatemodule/hashpair";
        pisc = strCdj + "native/checkboughtV2";
        eb = strCdj + "native/redeemInfo";
        mwew = strCdj + "native/useRedeem";
        cuep = strCdj + "native/paySuccess";
        qdd = strCdj + "alsolike";
        l9 = strCdj + "samedesign";
        lq1p = strCdj + "details/pageV2/%s";
        bk3 = strCdj + "native/favorite/my";
        ig = strKi + "safe/auth/addFavoriteV2";
        i97 = strKi + "safe/auth/delFavoriteV2";
        hm43 = strKi + "safe/auth/myPurchased/addManualHide";
        nh = strKi + "safe/auth/myPurchased/delManualHide";
        zky5 = strKi + "safe/auth/like/products";
        e0l = strKi + "safe/auth/delLike/products";
        iip = strCdj + "h5config";
        i7x = strKi + "getConfig";
        fd7p = strKi + "uipages/settings/wallpaper/V2";
        dymb = strKi + "uipages/settings/wallpaper/V3";
        i5c = strCdj + "native/gift/send";
        rst = strCdj + "native/gift/unbind";
        n2wl = strCdj + "native/gift/my";
        wj = strCdj + "native/gift/received";
        ha = strCdj + "native/gift/info";
        b03g = strCdj + "native/gift/use";
        gle = strCdj + "subject/gift/empty";
        oml3 = strCdj + "stats";
        v1uh = strKi + "safe/auth/allFree";
        mqz = strKi + "safe/uipages/theme/%s";
        sy9g = strKi + "uipages/theme/%s";
        woar = strKi + "comment/theme/%s";
        apb = strKi + "comment/theme/detail/%s";
        c59w = strKi + "comment/theme/input/%s";
        p69 = strKi + "safe/auth/comment/theme/%s";
        n9t = strKi + "safe/auth/comment/theme/%s/%s";
        gx4 = strKi + "safe/auth/comment/theme/like/%s/%s";
        ojf7 = strKi + "comment/theme/detail/%s/%s";
        p1s7 = strCdj + "wallpaper/tag/subscribe";
        gwj = strCdj + "wallpaper/tag";
        kyz8 = strCdj + "wallpaper";
        r58 = strKi + "coverPage";
        ft4 = strKi + "infowallpaper/recommend";
        qcx = strKi + "safe/auth/infowallpaper/like";
        tt = strKi + "safe/auth/social/follow/%s";
        rek = strKi + "safe/auth/social/list/users";
        eovq = strKi + "safe/auth/social/has/feed";
        ok4l = strKi + "safe/auth/social/list/feed";
        lk4 = strKi + "safe/auth/social/userInfo";
        l2gm = strKi + "safe/auth/operation/record";
    }
}
