package com.android.thememanager.basemodule.resource.constants;

import android.os.Build;
import com.android.thememanager.basemodule.utils.C1807g;
import com.android.thememanager.basemodule.utils.bf2;
import com.android.thememanager.basemodule.utils.o1t;
import com.android.thememanager.util.mcp;
import java.io.File;
import java.util.HashSet;
import java.util.Set;
import miui.app.constants.ThemeManagerConstants;
import miui.content.res.ThemeResources;
import miui.content.res.ThemeRuntimeManager;

/* JADX INFO: renamed from: com.android.thememanager.basemodule.resource.constants.q */
/* JADX INFO: compiled from: ThemeResourceConstants.java */
/* JADX INFO: loaded from: classes.dex */
public interface InterfaceC1789q extends com.android.thememanager.basemodule.resource.constants.toq, bf2.zy, ThemeManagerConstants {
    public static final int a6 = 0;
    public static final String ada = "com.android.thememanager:videowallpaper";
    public static final String ah9 = "/system/media/theme/default/wallpaper_default_dark.jpg";
    public static final String aof = "videowallpaper_launcher";
    public static final String aqx = "animation";
    public static final String avdu = "Clock_2x4";
    public static final String ax0p = "Font";
    public static final String b10b = "POP";
    public static final String b3 = "WIDGET";
    public static final String b4 = "framework-res";
    public static final String b5 = "spwallpaper";
    public static final String bn0 = "miwallpaper";
    public static final String bt9;
    public static final String[] bzx;
    public static final Set<String> c1f;
    public static final String c7aq = "photo_frame_2x4";
    public static final String c8 = "Icon";
    public static final String ce = "picPath";
    public static final String ch1s = "com.xiaomi.misettings";
    public static final String ci1g;
    public static final long cmzf = 16777216;
    public static final long cnx = -1;
    public static final String cp2 = "AOD";
    public static final String cph = "spaod";
    public static final String cs = "lockstyle_inner";
    public static final String cu = "/system/media/theme/.data/meta/%s/default.mrm";
    public static final String cv = "wallpaper/default_lock_wallpaper_inner.jpg";
    public static final int cz;
    public static final int d7 = 0;
    public static final int d8jh = 0;
    public static final long daa = 128;
    public static final String dbvq = ".mtz";
    public static final String dc = "rootPath";
    public static final int dd0 = 2;
    public static final String dg4q = "/system/media/theme/.data/preview/default/fold_home";
    public static final String dgf;
    public static final String dh74 = "launchstyle";
    public static final long dizt = 64;
    public static final String dp7j = "wallpaper/default_launcher_wallpaper_outer.jpg";
    public static final String dr6w = "title";
    public static final String dxb = "LockScreenWallpaper";
    public static final String dzu0;
    public static final String e0t = "com.android.thememanager.set_lockwallpaper";
    public static final String e1v = "ICONS";
    public static final String[] e6z;
    public static final int e95 = 0;
    public static final String ea7 = "miwallpaper_inner";
    public static final String eao0 = "largeicons";
    public static final String ef = "runtime_data.properties";
    public static final String ehbk = "videowallpaper_fold";
    public static final String ekha = "clock_1x2";
    public static final String ekiv = "com.android.contacts";
    public static final String elg;
    public static final String emvb = "wallpaper_fold";
    public static final int eqnj;
    public static final int ergk;
    public static final String eunr = "alarmscreen";
    public static final String ezv = "miwallpaper";
    public static final int f12b;
    public static final int f2;
    public static final String f32v = "com.android.thememanager";
    public static final String f6ja = "path";
    public static final String f6u2 = "/extraRingtoneInfo";
    public static final String f9 = "com.android.thememanager.theme_lock_live_wallpaper";
    public static final int faab = 0;
    public static final String fd23 = "LARGEICONS";
    public static final int fh1 = 0;
    public static final long fiyg = 32768;
    public static final int fl9j = 8;
    public static final String ftf = "miwallpaper_pad";
    public static final String fvoi = "videowallpaper_launcher";
    public static final String g0 = "WIDGET_SUIT";
    public static final String g2h = "PhotoFrame_2x2";
    public static final long g2p = 268435456;
    public static final String g45;
    public static final String g74f = "AlarmStyle";
    public static final String gc1 = "WIDGET_SUIT";
    public static final String gi = "/system/media/theme/default/lock_wallpaper_small";
    public static final long gkj = 256;
    public static final String gm = "icons_2x3";
    public static final String gq = "lockscreen_outer";
    public static final String gt = "spwallpaper";
    public static final String gu;
    public static final String gun = "clock_2x4";
    public static final String gvt = "com.android.thememanager.theme_lockwallpaper";
    public static final String gx2z = "lockstyle";

    @Deprecated
    public static final long h3 = 131072;
    public static final String h52g;
    public static final long h60v = 536870912;
    public static final int h8w0 = 0;
    public static final long hf94 = 134217728;
    public static final String hi2 = "miwallpaper_temp.mp4";
    public static final String hop = "com.miui.yellowpage";
    public static final String hx = "LockStyle";
    public static final long hxtt = 4;
    public static final String i0z = "com.android.thememanager.loopwallpaper";
    public static final String idkz = "spaod";

    /* JADX INFO: renamed from: if, reason: not valid java name */
    public static final long f46186if = 2097152;
    public static final int ifc = 0;
    public static final String ioq6;
    public static final String iq;
    public static final String iu = "wallpaper/default_lock_wallpaper.jpg";
    public static final long ivv9 = 4194304;
    public static final String iwp = "audioeffect";
    public static final String j2 = "FrameWork";
    public static final String j5 = "LARGEICONS_APP_CLASS_CARD";
    public static final String j59y = "com.android.thememanager.theme_lock_video_wallpaper";
    public static final String ja7 = "resourceList";
    public static final String jad = "/system/media/theme/default/lock_wallpaper";
    public static final String jci = "clock_3x4";
    public static final String jej = "com.android.settings";
    public static final String jf = "fonts";
    public static final String jk2b = "lockscreen_fold";
    public static final long jo = 33554432;
    public static final String jr = "lockstyle_inner";
    public static final long ju = 1024;
    public static final String jz7r;
    public static final String jzp = "Aod";
    public static final String k3 = "lockstyle_pad";
    public static final String k7u;
    public static final String k9 = "com.miui.home";
    public static final String kc = "LIVE_WALLPAPER";
    public static final long kd8 = 524288;
    public static final String klnv = "boots/bootaudio.mp3";
    public static final int km = 0;
    public static final String km71 = "HOVER";
    public static final int ks5;
    public static final String ksgr = "videowallpaper_fold";
    public static final String kuf = "lockscreen_inner";
    public static final String kus;
    public static final long l6 = 8;
    public static final String l7p;
    public static final String l8y = "widget";
    public static final String la = "/data/miui/precust_theme/";
    public static final long lnj = 8388608;
    public static final String lptj = "Launcher";
    public static final long lq96 = 16;
    public static final String lsos = "com.miui.home.freestyle";
    public static final int ltll = 2;
    public static final String luqn = "VIDEO_WALLPAPER";
    public static final String lwt = "miwallpaper.mp4";
    public static final String lww6 = "";
    public static final String ly = "Mms";
    public static final String m0ql = "miwallpaper_outer";
    public static final String m5 = "boots";
    public static final String m5h3 = "/system/media/theme/custom_online_ids.mrm";
    public static final String mam = "/system/media/theme/";
    public static final String mec;
    public static final int mh = 2;
    public static final String[] mkj5;
    public static final String mmdq = "AudioEffect";
    public static final String mnxh;
    public static final String mz;
    public static final String n026 = "extraRingtoneInfoKey";
    public static final String n1p9 = "SuperWallpaper";
    public static final String n1xt = "com.android.systemui";
    public static final String n3 = "boots/bootanimation.zip";
    public static final String n7c = "com_miui_miwallpaper_isVideoSupportEffect";
    public static final String ne = "ringtonePick";
    public static final int nhj = 0;
    public static final String no = "mmsringtone";
    public static final String noa = "wallpaper/default_wallpaper.jpg";
    public static final String nsiv = "com.miui.home.upside";
    public static final String[] nufx;
    public static final String nv = "/system/media/audio/ringtones/";
    public static final String nvn = "StatusBar";
    public static final String ny6p;
    public static final String o18 = "lockstyle_outer";
    public static final String o3u0 = "/system/media/theme/.data/meta/theme/";
    public static final String o703 = "/system/media/theme/.data/preview/default/preview_launcher_mask_h_0.png";
    public static final long o7w = 2;
    public static final String ob6y = "DeskWallpaper";
    public static final String oclb = "com.android.settings";
    public static final String oct = "com.android.thememanager:mamldataprovider";
    public static final String ogyu = "/system/media/theme/MILanProVF.mtz";
    public static final String oiz = "com.xiaomi.tv.gallerylockscreen.lockscreen_magazine_provider";
    public static final String ol = "/system/media/theme/.data/preview/default/preview_launcher_mask_v_0.png";
    public static final String ol6 = "_v12";
    public static final int op7r;
    public static final String ots = "launcher";
    public static final String ovu0 = "ringtones/notification.mp3";
    public static final String ow0 = "largeicons";
    public static final String p1;
    public static final String p3 = "splockscreen";
    public static final String p4 = "ringtones/ringtone.mp3";
    public static final String p9k9 = "/system/media/dynamic_video/";
    public static final String pg = "moduleId";
    public static final String ph;
    public static final String pi9r = "theme";
    public static final String pj7 = "_land.png";
    public static final String pp;
    public static final String psqy = "miui.systemui.plugin";
    public static final String pub6 = "_inner";
    public static final int px2 = 1;
    public static final String q0 = "Clock_1x2";
    public static final long q04 = 512;
    public static final Set<String> q28;
    public static final String q5x = "videowallpaper";
    public static final String q68 = "Compound";
    public static final int q8e = 0;
    public static final int q8n;
    public static final String qd7u = "videowallpaper_lockscreen";
    public static final String qf = "/data/miui/theme/";
    public static final int qhg7 = 0;
    public static final String qimr = "miwallpaper_outer";
    public static final String qjdr = "font_var_weight";
    public static final String qmbf;
    public static final String qp5l = "_vertical.png";
    public static final int qpih = 5;
    public static final String qsl8 = "mms";
    public static final int quc;
    public static final String qvnf = "lockscreen";
    public static final String qwyf = "statusbar";
    public static final long qx = 67108864;
    public static final String[] qxj;
    public static final String qzh = "/system/media/theme/default/wallpaper_default_small_dark.jpg";
    public static final int r1 = 0;
    public static final String r5c;
    public static final String re;
    public static final String rg;
    public static final String rnro;
    public static final int rpjx = 0;
    public static final String rxcq = "com.android.deskclock";

    @Deprecated
    public static final long rz = 65536;
    public static final String s08 = "/system/media/theme/.data/meta/";
    public static final String s4y = "/system/media/bootaudio.mp3";
    public static final long s7uw = 4096;
    public static final String sa1t = "largeicons";
    public static final String sfu = "ringtones/alarm.mp3";
    public static final String sh = "index";
    public static final String sly = "aod";
    public static final String so0v;
    public static final String sq2k = "WALLPAPER";
    public static final String ss2 = "Font";
    public static final String sttf;
    public static final long sw0 = 268435456;
    public static final String sxpt;
    public static final String t146;
    public static final String t4se = "alarmscreen";
    public static final String t7 = "AlarmAudio";
    public static final String t9 = "18:9";
    public static final String ta3f = "incallshow";
    public static final String tdgg = "/system/media/theme/.data/meta/theme/default.mrm";
    public static final int tjx = 0;
    public static final String tlw5 = "videowallpaper_lockscreen";
    public static final String tosv = "RINGTONE";
    public static final String ts4 = "MiWallpaper";
    public static final String tx;
    public static final String txs = "SuperWallpaper";
    public static final String txyb = "/data/system/users/0/lock_wallpaper";
    public static final String u07 = "/data/system/users/0/wallpaper";
    public static final String u0t = "/system/media/lockscreen/video/video_wallpaper_thumbnail.jpg";
    public static final String u3 = "Contact";
    public static final String u7l5 = "icons";
    public static final String ua = "NotificationAudio";
    public static final long ub = 134217728;
    public static final String uc1 = "extraRingtoneInfoTitleKey";
    public static final int uciq = 0;
    public static final String uey;
    public static final String[] uod;
    public static final String upj2;
    public static final String usxh = "support_new_miwallpaper";
    public static final String uux;
    public static final String uz6 = "/sdcard/Android/data/com.android.thememanager/";
    public static final String v5 = "photo_frame_4x4";
    public static final String v6 = "THEME";
    public static final String v70n = "RingtoneAudio";
    public static final String v9zx = "_outer";
    public static final String vc7p;
    public static final String vcky = "ringtones";
    public static final String vjz = "/system/media/lockscreen/video/";
    public static final String vllq = "Clock_2x2";
    public static final String vmj = "wallpaper_inner";
    public static final String vn7 = "wallpaper/default_launcher_wallpaper_inner.jpg";
    public static final int vs4 = 0;
    public static final String vt = "title";
    public static final String vt2p;
    public static final int vx9l = 0;
    public static final String vyj = "wallpaper_outer";
    public static final String w5 = "clock_2x2";
    public static final String w8g = "wallpaper/default_lock_wallpaper_outer.jpg";
    public static final String w95 = "miwallpaper_inner";
    public static final long wr3 = 16;
    public static final String wx3a = "BootAudio";
    public static final String wz = "calendarringtone";
    public static final String x0 = "loop_lock_wallpaper_gallery_when_super_or_maml_enable";
    public static final String xb = "0";
    public static final String xk3 = "com.android.mms";
    public static final String xtyc = "/system/media/theme/.data/meta/custom/custom.mrm";
    public static final String xx8g = "/system/media/theme/.data/preview/default/preview_launcher_mask_0.png";
    public static final long xz = 8192;
    public static final long y0yf = 32;
    public static final String y380 = "com.miui.miwallpaper.";
    public static final String y3rt;
    public static final String y53 = "canNotPlay";
    public static final long y5s = 262144;
    public static final String y6 = "dynamicvideowallpaper";
    public static final int y7;
    public static final String y9h3 = "icons_4x3";
    public static final String y9i5 = "/system/media/lockscreen/video/video_wallpaper.mp4";
    public static final String y9o6 = "lockscreen";
    public static final String yad = "fonts";
    public static final String yb3p = "contact";
    public static final String yc = "com.android.thememanager:timeline";
    public static final String[] ygct;
    public static final String yi = "splockscreen";
    public static final long yir = 16384;
    public static final String yj1 = "/system/media/theme/.data/preview/default/";
    public static final String ym5 = "Largeicon";
    public static final String ymez = "aod";
    public static final String yv44 = "PhotoFrame_4x4";
    public static final String yvd = "lockstyle_outer";
    public static final String yy = "widget_suit";
    public static final String yza;
    public static final String yzg4;
    public static final long yzy = 2048;
    public static final String z2 = "FONT";
    public static final String z5tq = "wallpaper";
    public static final int z79v;
    public static final String zac;
    public static final String zdb0 = "com.miui.home.none_provider";
    public static final String zdev = "com.android.thememanager.set_lock_maml_wallpaper";
    public static final String zg = "PhotoFrame_2x4";
    public static final String ziq = "thumbnailPath";
    public static final String zjr = "BootAnimation";
    public static final String zne = "Video_Wallpaper";
    public static final long zsm2 = 1048576;
    public static final long zwh = 1;
    public static final String zx6 = "photo_frame_2x2";
    public static final String[] nh83 = {"ringtone", com.android.thememanager.basemodule.analysis.toq.mle, "alarm"};
    public static final String iws = "Font.ttf";
    public static final String igu = "fonts/Roboto-Regular.ttf";
    public static final String adn = "fonts/DroidSans.ttf";
    public static final String dlv = "fonts/Arial.ttf";
    public static final String[] kzk = {iws, igu, adn, dlv};
    public static final String tsm = "FontFallback.ttf";
    public static final String xd = "fonts/DroidSansFallback.ttf";
    public static final String[] gr = {tsm, xd};

    /* JADX INFO: renamed from: com.android.thememanager.basemodule.resource.constants.q$k */
    /* JADX INFO: compiled from: ThemeResourceConstants.java */
    class k extends HashSet<String> {
        k() {
            add("spwallpaper");
            add("splockscreen");
            add("spaod");
        }
    }

    /* JADX INFO: renamed from: com.android.thememanager.basemodule.resource.constants.q$toq */
    /* JADX INFO: compiled from: ThemeResourceConstants.java */
    class toq extends HashSet<String> {
        toq() {
            add("wallpaper");
            add("miwallpaper");
            add("videowallpaper");
            add(InterfaceC1789q.y6);
        }
    }

    static {
        StringBuilder sb = new StringBuilder();
        String str = bf2.zy.oaex;
        sb.append(str);
        sb.append(b4);
        mz = sb.toString();
        rg = str + "wallpaper";
        sxpt = str + bf2.f57718qrj;
        yza = str + "lock_wallpaper_small";
        bt9 = str + igu;
        rnro = str + xd;
        uux = ThemeRuntimeManager.RUNTIME_PATH_BOOT_ANIMATION;
        elg = str + klnv;
        ph = str + p4;
        ci1g = str + ovu0;
        qmbf = str + sfu;
        re = str + "lockscreen";
        y3rt = str + k9;
        kus = str + "com.android.systemui";
        ioq6 = str + "com.android.contacts";
        so0v = str + "com.android.mms";
        tx = str + iwp;
        zac = str + "miwallpaper";
        k7u = str + "alarmscreen";
        vt2p = str + "icons";
        String str2 = bf2.zy.vh;
        g45 = str2;
        dzu0 = new File(str2).getName();
        gu = str + jci;
        mnxh = ThemeResources.THEME_MAGIC_PATH + "spwallpaper";
        iq = ThemeResources.THEME_MAGIC_PATH + "splockscreen";
        l7p = ThemeResources.THEME_MAGIC_PATH + "spaod";
        q28 = new k();
        c1f = new toq();
        String[] strArrM9878q = {"alarm", iwp, "bootanimation", "bootaudio", yb3p, "fonts", "framework", "icons", "launcher", "lockscreen", gx2z, "mms", com.android.thememanager.basemodule.analysis.toq.mle, "ringtone", qwyf, "wallpaper", "miwallpaper", "alarmscreen", ekha, w5, gun, "photoframe_2x2", "photoframe_2x4", "photoframe_4x4", "com.android.settings", "aod", "spaod", "splockscreen", "spwallpaper"};
        ygct = strArrM9878q;
        if (C1807g.m7081r()) {
            strArrM9878q = mcp.m9878q();
        }
        bzx = strArrM9878q;
        nufx = new String[]{"wallpaper", "lockscreen", "ringtone", com.android.thememanager.basemodule.analysis.toq.mle, "alarm"};
        int iM7181n = o1t.C1820k.m7181n();
        ergk = iM7181n;
        if (iM7181n == 7) {
            iM7181n = 6;
        } else if (iM7181n == o1t.C1820k.f10395y || iM7181n == o1t.C1820k.f10392p || iM7181n == o1t.C1820k.f10394s || iM7181n == o1t.C1820k.f57802ld6) {
            iM7181n = 10;
        }
        y7 = iM7181n;
        z79v = iM7181n;
        cz = iM7181n;
        int i2 = o1t.C1820k.m7181n() > 8 ? iM7181n : 6;
        f2 = i2;
        eqnj = i2;
        q8n = iM7181n;
        ks5 = iM7181n;
        f12b = i2;
        quc = i2;
        op7r = i2;
        mkj5 = new String[]{ekha, w5, gun, zx6, c7aq, v5, "fonts", "animation", "miwallpaper", "icons"};
        e6z = new String[]{"spaod", "splockscreen", "spwallpaper", "aod", gx2z, "launcher", "miwallpaper", "framework", qwyf, yb3p, "mms", "icons", ekha, w5, gun, "photoframe_2x2", "photoframe_2x4", "photoframe_4x4", "bootanimation", "fonts", "alarmscreen", "largeicons"};
        qxj = new String[]{iwp, "wallpaper", "lockscreen", "ringtone", "alarm", com.android.thememanager.basemodule.analysis.toq.mle, "bootaudio"};
        uod = new String[]{"framework", gx2z, qwyf, "launcher", yb3p, "mms"};
        StringBuilder sb2 = new StringBuilder();
        String str3 = com.android.thememanager.basemodule.resource.constants.toq.y1e;
        sb2.append(str3);
        sb2.append("theme/");
        String string = sb2.toString();
        dgf = string;
        upj2 = str3 + "theme/.data/meta/";
        ny6p = str3 + "theme/.data/meta/theme/";
        vc7p = str3 + "audio/ringtones/";
        StringBuilder sb3 = new StringBuilder();
        String str4 = com.android.thememanager.basemodule.resource.constants.toq.anfo;
        sb3.append(str4);
        sb3.append("theme/");
        t146 = sb3.toString();
        jz7r = str4 + "theme/.data/meta/";
        pp = str4 + "theme/.data/meta/theme/";
        p1 = string + "operator/" + ef;
        StringBuilder sb4 = new StringBuilder();
        sb4.append(ThemeResources.THEME_MAGIC_PATH);
        sb4.append("disable_operator_animation");
        uey = sb4.toString();
        mec = ThemeResources.THEME_MAGIC_PATH + "disable_operator_audio";
        StringBuilder sb5 = new StringBuilder();
        sb5.append(Build.VERSION.SDK_INT >= 33 ? "/product" : "/system");
        sb5.append("/etc/precust_theme/");
        String string2 = sb5.toString();
        sttf = string2;
        if (new File(la).exists()) {
            string2 = la;
        }
        yzg4 = string2;
        h52g = string2 + "precust.zip";
        r5c = ThemeResources.DISABLE_PROVISION_THEME;
    }
}
