package com.android.thememanager.basemodule.resource.constants;

import android.os.Build;
import miui.app.constants.ResourceBrowserConstants;
import miuix.os.f7l8;

/* JADX INFO: compiled from: ResourceConstants.java */
/* JADX INFO: loaded from: classes.dex */
public interface toq extends ResourceBrowserConstants {
    public static final String a2lv;
    public static final String anfo;
    public static final String bhh = "lockscreen_";
    public static final String bt4 = ".zip";
    public static final String cax = ".cache/resource/";
    public static final int cj = 90;
    public static final String d79j = "recommend/";
    public static final String dcmf = "cache_theme_home_preview";
    public static final String dmt = ".import";
    public static final String dt = ".mp4";
    public static final String e1 = "preview_icons_2x3_";
    public static final String e2 = "/system/media/lockscreen/";
    public static final String em44 = "da39a3ee5e6b4b0d3255bfef95601890afd80709";
    public static final String f5k = "description";
    public static final String fd = ".mrf";
    public static final String fyt = "version";
    public static final int g7 = 100;
    public static final String ga8 = "home_preview.png";
    public static final String gj = "preview_lockscreen_";
    public static final String gm3 = "version/";
    public static final String he = "list/";
    public static final String hze4 = "android.resource://";
    public static final String ik8 = "association/";
    public static final String jf5c = "preview_";
    public static final long jun = 52428800;
    public static final int k68d = 90;
    public static final String k8s = "thumbnail/";
    public static final String kncy;
    public static final String kqo = "/system/media/wallpaper/fold_wallpaper_group";
    public static final String ktm = "/system/media/audio/alarms/";
    public static final String kx = "module_config.xml";
    public static final int kxe = 90;
    public static final String kxp3 = "title";
    public static final String lb = ".tmpXres";
    public static final String lb8 = "b004d74e-5c49-430c-bb6a-18ed5d2d33e4";
    public static final String lbq = "rightsDescription";
    public static final int leq = 70;
    public static final String lo8 = ".data/";
    public static final String lt = "description.xml";
    public static final String lvt = "package.xml";
    public static final String m6t = "/system/media/audio/notifications/";
    public static final String mpq = "preview_launcher_";
    public static final String mxfl = "author";
    public static final String n5 = ".mrm";
    public static final int n54 = 100;
    public static final String n7 = "_wallpaper.jpg";
    public static final String n96 = "_&_";
    public static final String nfw3 = "theme";
    public static final String nngj = "launcher_";
    public static final String nt = "preview";
    public static final String nyhr = "_lockscreen.jpg";
    public static final String o9qk = "com.android.thememanager.fileprovider";
    public static final String olea = "preview_icons_4x3";
    public static final String oz47 = "designer";
    public static final String pm14 = ".mp3";
    public static final String puh = "page/";
    public static final String pwca = "cover";
    public static final String q28p = "rights/";
    public static final String q6x = "detail/";
    public static final String q92d = "content/";
    public static final String qode = "home_preview_v.png";
    public static final String qp0k = "MILanProVF";
    public static final String re5;
    public static final String ru = "/system/media/";
    public static final int rugz = 1;
    public static final String rv = "preview";
    public static final String szp = ".zip";
    public static final String tl = "version";
    public static final String trbh = "/system/media/wallpaper/wallpaper_group";
    public static final String tsz9 = "%s_%s_";
    public static final String u02j = "home_preview_h.png";
    public static final String upv = "%s_%s_small_";
    public static final String v6we;
    public static final String v7p = "hint/";
    public static final String vm8 = ".mrc";
    public static final String vuk = ".mra";
    public static final String vy5c = "^(preview|[a-z]{2}_[A-Z]{2})_([0-9a-zA-Z_]+)_([0-9]+)\\.(png|jpg)$";
    public static final String w1k2;
    public static final float w5fh = 0.52f;
    public static final long w6 = 52428800;
    public static final String wc6 = "/system/media/wallpaper/";
    public static final String wjzm = "/system/media/audio/ringtones/";
    public static final String x0yo = "meta/";
    public static final String x3b5 = "custHolder";
    public static final String xdbo = "plugin_config.xml";
    public static final String xwma = "preview/";
    public static final String y1e;
    public static final String y9 = "/system/media/wallpaper/fold_wallpaper_group/default_sensor_wallpaper_config.json";
    public static final String ybu = ".jpg";
    public static final String ytul = ".temp/";
    public static final int z7 = 30;
    public static final String z7zz = "preview/";
    public static final String zn;
    public static final String zq = "platform";
    public static final String zvv = "download/";

    static {
        String str = f7l8.toq("ro.miui.has_cust_partition", false) ? "/cust/cust/" : "/data/miui/cust/";
        w1k2 = str;
        String str2 = str + x3b5 + "/";
        y1e = str2;
        v6we = str2 + C1788k.f10189y;
        a2lv = str2 + "lockscreen/";
        kncy = str2 + "audio/ringtones/";
        re5 = str2 + "audio/notifications/";
        zn = str2 + "audio/alarms/";
        StringBuilder sb = new StringBuilder();
        sb.append(Build.VERSION.SDK_INT >= 33 ? "/product" : "/system");
        sb.append("/etc/precust_theme/");
        anfo = sb.toString();
    }
}
